challengegui:
  1-day:
    material: IRON_BLOCK
    name: "&2In 1 day"
    slot: 11
    days: 1
  2-day:
    material: GOLD_BLOCK
    name: "&2In 2 days"
    slot: 13
    days: 2
  3-day:
    material: DIAMOND_BLOCK
    name: "&2In 3 days"
    slot: 15
    days: 3
#  0.0002-day:
#    material: IRON_BLOCK
#    name: "&2In about 10 sec (TEST)"
#    slot: 5
#  0.0008-day:
#    material: IRON_BLOCK
#    name: "&2In 1 min (TEST)"
#    slot: 6
#    days: 0.0008
items:
  dchip:
    material: PRISMARINE_CRYSTALS
    name: "&fDiamond Chip"
    glow: true
    custom-model-data: 48720
    update: 1
  blazesword:
    material: GOLDEN_SWORD
    name: "&6Blaze Sword"
    enchants:
      SHARPNESS: 8
      FIRE_ASPECT: 3
      UNBREAKING: 10
    custom-model-data: 48721
    lore:   
      - ""
      - "&cRight-click while holding this flaming"
      - "&cweapon to shoot 3 fireballs in quick"
      - "&csuccession at your enemies. This ability"
      - "&chas a &610s &ccooldown."
    update: 3
    ability:
      name: "Fireball Trio"
      cooldown: 10
      yield: 1
      randomness: 0.05
  tanto:
    material: STONE_SWORD
    name: "&aTantō"
    custom-model-data: 48722
    lore:   
      - ""
      - "&eA short sword that can be"
      - "&eswung extremely fast."
    update: 2
    attributes:
      GENERIC_ATTACK_DAMAGE:
        name: "Attack Damage"
        operation: ADD_NUMBER
        amount: 4
        slot: HAND
      GENERIC_ATTACK_SPEED:
        name: "Attack Speed"
        operation: ADD_NUMBER
        amount: 16
        slot: HAND
  orcus:
    material: NETHERITE_HOE
    name: "&1Orcus"
    custom-model-data: 48723
    lore:
      - ""
      - "&eThis scythe was once wielded by the"
      - "&egod of death himself. Land a critical"
      - "&ehit on an enemy player to remove"
      - "&620% &eof their remaining health, and"
      - "&etemporarily blind and wither them."
      - "&eThis ability has a &630s &ecooldown."
    enchants:
      SHARPNESS: 10
      CURSE_OF_VANISHING: 1
    update: 3
    ability:
      name: "Lifesteal"
      cooldown: 30
      percent: 20
  shadowblade:
    material: DIAMOND_SWORD
    name: "&5Shadowblade"
    custom-model-data: 48724
    lore:
      - ""
      - "&dHarness the power of the barren"
      - "&dwasteland of the End. Right-click"
      - "&dto teleport &f10 blocks &din the"
      - "&ddirection you are looking. If you"
      - "&dteleport through a player, you will"
      - "&dautomatically face that player."
      - "&dThis ability has a &f20s &dcooldown."
    update: 3
    ability:
      name: "Blink"
      cooldown: 20
      distance: 10
  oxtailsaber:
    material: IRON_SWORD
    name: "&6Oxtail Saber"
    custom-model-data: 48725
    lore:   
      - ""
      - "&eDual wield this weapon to attack"
      - "&eenemies twice as fast, halving"
      - "&etheir damage tick cooldown."
    update: 2
    attributes:
      GENERIC_ATTACK_DAMAGE:
        name: "Attack Damage"
        operation: ADD_NUMBER
        amount: 5
        slot: HAND
      GENERIC_ATTACK_SPEED:
        name: "Attack Speed"
        operation: ADD_NUMBER
        amount: -0.7
        slot: HAND
    ability:
      name: "Dual"
      cooldown: 0
  shiruken:
    material: NETHER_STAR
    name: "&6Shiruken"
    custom-model-data: 48726
    lore:
      - ""
      - "&eA throwable weapon that damages"
      - "&eenemies extremely rapidly. Drops"
      - "&eas an item after hitting a block"
      - "&eor enemy."
    update: 3
    ability:
      name: "Shiruken"
      cooldown: 0
      speed: 3
      damage: 1
      ticks: 10
capture-exclude:
  - ENDER_DRAGON
  - WITHER
  - ELDER_GUARDIAN
  - WARDEN