challengegui:
  1-day:
    material: IRON_BLOCK
    name: "&2In 1 day"
    slot: 11
    days: 1
  2-day:
    material: GOLD_BLOCK
    name: "&2In 2 days"
    slot: 13
    days: 2
  3-day:
    material: DIAMOND_BLOCK
    name: "&2In 3 days"
    slot: 15
    days: 3
#  0.0002-day:
#    material: IRON_BLOCK
#    name: "&2In about 10 sec (TEST)"
#    slot: 5
#  0.0008-day:
#    material: IRON_BLOCK
#    name: "&2In 1 min (TEST)"
#    slot: 6
#    days: 0.0008
items:
  dchip:
    material: PRISMARINE_CRYSTALS
    name: "&fDiamond Chip"
    enchants:
      UNBREAKING: 1
    flags: 
      - HIDE_ENCHANTS
    custom-model-data: 48720
  blazesword:
    material: GOLDEN_SWORD
    name: "&6Blaze Sword"
    enchants:
      SHARPNESS: 8
      FIRE_ASPECT: 3
      UNBREAKING: 10
    custom-model-data: 48721
    lore:   
      - ""
      - "&cRight-click while holding this flaming"
      - "&cweapon to shoot 3 fireballs in quick"
      - "&csuccession at your enemies. This ability"
      - "&chas a &610 second &ccooldown."
capture-exclude:
  - ENDER_DRAGON
  - WITHER
  - ELDER_GUARDIAN
  - WARDEN