challengegui:
  1-day:
    material: IRON_BLOCK
    name: "&2In 1 day"
    slot: 11
    days: 1
  2-day:
    material: GOLD_BLOCK
    name: "&2In 2 days"
    slot: 13
    days: 2
  3-day:
    material: DIAMOND_BLOCK
    name: "&2In 3 days"
    slot: 15
    days: 3
#  0.0002-day:
#    material: IRON_BLOCK
#    name: "&2In about 10 sec (TEST)"
#    slot: 5
#  0.0008-day:
#    material: IRON_BLOCK
#    name: "&2In 1 min (TEST)"
#    slot: 6
#    days: 0.0008
recipegui:
  next:
    material: ARROW
    name: "&fNext Page"
  prev:
    material: ARROW
    name: "&fPrevious Page"
  fill:
    material: BLACK_STAINED_GLASS_PANE
    name: ""
  locked:
    material: BARRIER
    name: "&cLocked"
    lore:
      - "&7You cannot use this recipe yet!"
capture-exclude:
  - ENDER_DRAGON
  - WITHER
  - ELDER_GUARDIAN
  - WARDEN
skaddon:
  limit_warn_start: 5
  # Time to count down to for restock | Must be "HH:mm:ss" format
  restock_time: "00:00:00"
items:
  obsidianingot:
    material: NETHERITE_INGOT
    name: "&5Obsidian Ingot"
    glow: true
    custom-model-data: 48743
    chance: 0.2 # out of 1
    update: 1
    lore:
      - "&7A rare ingredient dropped when"
      - "&7the blast resistance of obsidian"
      - "&7is overcome."
  dchip:
    material: PRISMARINE_CRYSTALS
    name: "&fDiamond Chip"
    glow: true
    custom-model-data: 48720
    update: 1
  blazesword:
    material: GOLDEN_SWORD
    name: "&6Blaze Sword"
    enchants:
      FIRE_ASPECT: 3
    flags:
      - HIDE_ATTRIBUTES
    custom-model-data: 48721
    lore:
      - ""
      - "&cRight-click while holding this flaming"
      - "&cweapon to shoot 3 fireballs in quick"
      - "&csuccession at your enemies. This ability"
      - "&chas a &610s &ccooldown."
      - ""
      - "&7When in Main Hand:"
      - "&2 7 Attack Damage"
      - "&2 1.6 Attack Speed"
    update: 2
    durability: 500
    attributes:
      GENERIC_ATTACK_DAMAGE:
        name: "Attack Damage"
        operation: ADD_NUMBER
        amount: 6
        slot: HAND
      GENERIC_ATTACK_SPEED:
        name: "Attack Speed"
        operation: ADD_NUMBER
        amount: -2.33
        slot: HAND
    ability:
      name: "Fireball Trio"
      cooldown: 10
      yield: 1
      randomness: 0.05
  tanto:
    material: STONE_SWORD
    name: "&aTantō"
    custom-model-data: 48722
    lore:
      - ""
      - "&eA short sword that can be"
      - "&eswung extremely fast."
      - ""
      - "&7When in Main Hand:"
      - "&2 5 Attack Damage"
      - "&2 20 Attack Speed"
    update: 2
    flags:
      - HIDE_ATTRIBUTES
    attributes:
      GENERIC_ATTACK_DAMAGE:
        name: "Attack Damage"
        operation: ADD_NUMBER
        amount: 4
        slot: HAND
      GENERIC_ATTACK_SPEED:
        name: "Attack Speed"
        operation: ADD_NUMBER
        amount: 16
        slot: HAND
  orcus:
    material: NETHERITE_HOE
    name: "&1Orcus"
    custom-model-data: 48723
    lore:
      - ""
      - "&eThis scythe was once wielded by the"
      - "&egod of death himself. Land a critical"
      - "&ehit on an enemy player to remove"
      - "&620% &eof their remaining health, and"
      - "&etemporarily blind and wither them."
      - "&eThis ability has a &630s &ecooldown."
    enchants:
      SHARPNESS: 10
      VANISHING_CURSE: 1
    update: 3
    ability:
      name: "Lifesteal"
      cooldown: 30
      percent: 20
  shadowblade:
    material: DIAMOND_SWORD
    name: "&5Shadowblade"
    custom-model-data: 48724
    lore:
      - ""
      - "&dHarness the power of the barren"
      - "&dwasteland of the End. Right-click"
      - "&dto teleport &f10 blocks &din the"
      - "&ddirection you are looking. If you"
      - "&dteleport through a player, you will"
      - "&dautomatically face that player."
      - "&dThis ability has a &f20s &dcooldown."
    update: 3
    ability:
      name: "Blink"
      cooldown: 20
      distance: 10
  oxtailsaber:
    material: IRON_SWORD
    name: "&6Oxtail Saber"
    custom-model-data: 48725
    lore:
      - ""
      - "&eDual wield this weapon to attack"
      - "&eenemies twice as fast, halving"
      - "&etheir damage tick cooldown."
      - ""
      - "&7When in Main Hand:"
      - "&2 6 Attack Damage"
      - "&2 3.3 Attack Speed"
    update: 2
    flags:
      - HIDE_ATTRIBUTES
    attributes:
      GENERIC_ATTACK_DAMAGE:
        name: "Attack Damage"
        operation: ADD_NUMBER
        amount: 5
        slot: HAND
      GENERIC_ATTACK_SPEED:
        name: "Attack Speed"
        operation: ADD_NUMBER
        amount: -0.66
        slot: HAND
    ability:
      name: "Dual"
      cooldown: 0
  shiruken:
    material: NETHER_STAR
    name: "&6Shiruken"
    custom-model-data: 48726
    lore:
      - ""
      - "&eA throwable weapon that damages"
      - "&eenemies in rapid bursts. Drops"
      - "&eas an item after hitting a block"
      - "&eor enemy."
    update: 3
    ability:
      name: "Shiruken"
      cooldown: 2
      speed: 3
      damage: 1
      ticks: 20
  mithril:
    lore:
      - ""
      - "&eA light, flexible, yet durable set"
      - "&eof armor. Each piece, when worn,"
      - "&egives &6+0.5% &emovement speed per"
      - "&elevel of &bAgility &eabove 25."
    scaled-attribute:
      skill: AGILITY
      type: GENERIC_MOVEMENT_SPEED
      name: "Speed"
      operation: MULTIPLY_SCALAR_1
      amount: 0.005
    helmet:
      material: CHAINMAIL_HELMET
      name: "&7&lMithril Helmet"
      custom-model-data: 48727
      durability: 400
      update: 3
    chestplate:
      material: CHAINMAIL_CHESTPLATE
      name: "&7&lMithril Chestplate"
      custom-model-data: 48728
      durability: 600
      update: 3
    leggings:
      material: CHAINMAIL_LEGGINGS
      name: "&7&lMithril Leggings"
      custom-model-data: 48729
      durability: 550
      update: 3
    boots:
      material: CHAINMAIL_BOOTS
      name: "&7&lMithril Boots"
      custom-model-data: 48730
      durability: 500
      update: 3
  obsidian:
    lore:
      - ""
      - "&eForged from the the most fortified"
      - "&eobsidian of the depths, each piece"
      - "&eof this near-imperishable armor set,"
      - "&ewhen worn, gives &6+0.2 &earmor"
      - "&etoughness per level of &bEndurance"
      - "&eabove 25, increasing its resistance"
      - "&eagainst high damage sources."
    scaled-attribute:
      skill: ENDURANCE
      type: GENERIC_ARMOR_TOUGHNESS
      name: "Armor Toughness"
      operation: ADD_NUMBER
      amount: 0.2
    helmet:
      material: LEATHER_HELMET
      name: "&5Obsidian Helmet"
      custom-model-data: 48731
      color: "61,40,86"
      flags:
        - HIDE_DYE
      durability: 800
      update: 3
    chestplate:
      material: LEATHER_CHESTPLATE
      name: "&5Obsidian Chestplate"
      custom-model-data: 48732
      color: "40,31,63"
      flags:
        - HIDE_DYE
      durability: 1200
      update: 3
    leggings:
      material: LEATHER_LEGGINGS
      name: "&5Obsidian Leggings"
      custom-model-data: 48733
      color: "17,13,29"
      flags:
        - HIDE_DYE
      durability: 1100
      update: 3
    boots:
      material: LEATHER_BOOTS
      name: "&5Obsidian Boots"
      custom-model-data: 48734
      color: "6,3,12"
      flags:
        - HIDE_DYE
      durability: 1000
      update: 3
  infused:
    lore:
      - ""
      - "&eUnleash the power of copper-infused"
      - "&estrength. Each piece of this set, when"
      - "&eworn, gives &6+0.5% &eattack damage per"
      - "&elevel of &bFighting &eabove 25."
    scaled-attribute:
      skill: FIGHTING
      type: GENERIC_ATTACK_DAMAGE
      name: "Attack Damage"
      operation: MULTIPLY_SCALAR_1
      amount: 0.005
    helmet:
      material: LEATHER_HELMET
      name: "&6Infused Helmet"
      custom-model-data: 48735
      color: "223,127,104"
      flags:
        - HIDE_DYE
      durability: 350
      update: 3
    chestplate:
      material: LEATHER_CHESTPLATE
      name: "&6Infused Chestplate"
      custom-model-data: 48736
      color: "196,154,86"
      flags:
        - HIDE_DYE
      durability: 525
      update: 3
    leggings:
      material: LEATHER_LEGGINGS
      name: "&6Infused Leggings"
      custom-model-data: 48737
      color: "156,177,106"
      flags:
        - HIDE_DYE
      durability: 475
      update: 3
    boots:
      material: LEATHER_BOOTS
      name: "&6Infused Boots"
      custom-model-data: 48738
      color: "114,192,152"
      flags:
        - HIDE_DYE
      durability: 425
      update: 3
  shard:
    lore:
      - ""
      - "&eImbue yourself with the healing"
      - "&epowers of amethyst. Each piece of"
      - "&ethis set, when worn, gives &6+0.1 &emax"
      - "&ehealth per level of &bMining &eabove 25."
    scaled-attribute:
      skill: MINING
      type: GENERIC_MAX_HEALTH
      name: "Max Health"
      operation: ADD_NUMBER
      amount: 0.1
    helmet:
      material: LEATHER_HELMET
      name: "&dShard Helmet"
      custom-model-data: 48739
      color: "255,252,211"
      flags:
        - HIDE_DYE
      durability: 350
      update: 3
    chestplate:
      material: LEATHER_CHESTPLATE
      name: "&dShard Chestplate"
      custom-model-data: 48740
      color: "253,203,229"
      flags:
        - HIDE_DYE
      durability: 525
      update: 3
    leggings:
      material: LEATHER_LEGGINGS
      name: "&dShard Leggings"
      custom-model-data: 48741
      color: "196,141,235"
      flags:
        - HIDE_DYE
      durability: 475
      update: 3
    boots:
      material: LEATHER_BOOTS
      name: "&dShard Boots"
      custom-model-data: 48742
      color: "163,118,236"
      flags:
        - HIDE_DYE
      durability: 425
      update: 3
