main: com.leomelonseeds.ultimaaddons.UltimaAddons
name: UltimaAddons
version: "1.4"
api-version: 1.20
author: M310N
description: Extra features for Ultima
depend:
  - Kingdoms
  - PlaceholderAPI
  - AdvancedEnchantments
  - Shopkeepers
  - AdvancedRegionMarket
  - Vault
  - WorldEdit
  - AuraSkills
softdepend:
  - LevelledMobs
  - CoreProtect
  - BetterRTP
  - DiscordSRV
commands:
  uchallenge: { }
  recipes: { }
  uintro: { }
  udropparty:
    default: op
  ugive:
    default: op
  ureload:
    default: op
  usk:
    default: op
  uenchant:
    default: op
  utoggleshulkers:
    default: op
permissions:
  ua.admin: { }
