main: com.leomelonseeds.ultimaaddons.UltimaAddons
name: UltimaAddons
version: "1.3"
api-version: 1.20
author: M310N
description: Extra features for Ultima
depend:
- Kingdoms
- DiscordSRV
- PlaceholderAPI
- AdvancedEnchantments
commands: 
  uchallenge: {}