challengegui:
  1day:
    item: IRON_BLOCK
    name: "&2In 1 day"
    slot: 11
    days: 1
  2day:
    item: GOLD_BLOCK
    name: "&2In 2 days"
    slot: 13
    days: 2
  3day:
    item: DIAMOND_BLOCK
    name: "&2In 3 days"
    slot: 15
    days: 3
  e:
    item: IRON_BLOCK
    name: "&2In about 10 sec (TEST)"
    slot: 5
    days: 0.0002
  f:
    item: IRON_BLOCK
    name: "&2In 1 min (TEST)"
    slot: 6
    days: 0.0008